-- ============================================
-- 게임 테스트용 더미 데이터 (테이블 생성 포함)
-- ============================================

-- 1. 시퀀스 생성 (이미 있으면 무시)
CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_GAME_ROOM
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_GAME_JOIN
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 2. 테이블 생성 (이미 있으면 무시)
-- TBL_USER 테이블
CREATE TABLE TBL_USER (
    ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    USER_BIRTHDAY DATE,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_PHONE VARCHAR2(20),
    USER_PASSWORD VARCHAR2(255),
    USER_NICKNAME VARCHAR2(50) NOT NULL,
    USER_PROVIDER VARCHAR2(20) DEFAULT 'LOCAL',
    USER_THUMBNAIL_NAME VARCHAR2(255),
    USER_THUMBNAIL_URL VARCHAR2(500),
    USER_EXP NUMBER DEFAULT 0,
    USER_LEVEL NUMBER DEFAULT 1
);

-- TBL_GAME_ROOM 테이블
CREATE TABLE TBL_GAME_ROOM (
    ID NUMBER PRIMARY KEY,
    GAME_ROOM_TITLE VARCHAR2(100),
    GAME_ROOM_IS_TEAM NUMBER(1) DEFAULT 0,
    GAME_ROOM_TYPE VARCHAR2(50),
    GAME_ROOM_IS_OPEN NUMBER(1) DEFAULT 1,
    GAME_ROOM_MAX_PLAYER NUMBER DEFAULT 4,
    GAME_ROOM_IS_START NUMBER(1) DEFAULT 0,
    GAME_ROOM_PASS_KEY VARCHAR2(100),
    GAME_ROOM_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- TBL_GAME_JOIN 테이블
CREATE TABLE TBL_GAME_JOIN (
    ID NUMBER PRIMARY KEY,
    GAME_JOIN_IS_HOST NUMBER(1) DEFAULT 0,
    USER_ID NUMBER NOT NULL,
    GAME_ROOM_ID NUMBER NOT NULL,
    GAME_JOIN_TEAMCOLOR VARCHAR2(20),
    GAME_JOIN_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    GAME_JOIN_IS_TURN NUMBER(1) DEFAULT 0,
    GAME_JOIN_POSITION NUMBER DEFAULT 0,
    GAME_JOIN_IS_READY NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_GAME_JOIN_ROOM FOREIGN KEY (GAME_ROOM_ID) REFERENCES TBL_GAME_ROOM(ID),
    CONSTRAINT FK_GAME_JOIN_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID)
);

-- 3. 더미 유저 데이터 (4명)
-- 컬럼 순서: ID, USER_NAME, USER_BIRTHDAY, USER_EMAIL, USER_PHONE, USER_PASSWORD, USER_NICKNAME, USER_PROVIDER, USER_THUMBNAIL_NAME, USER_THUMBNAIL_URL, USER_EXP, USER_LEVEL
INSERT INTO TBL_USER VALUES (SEQ_USER.NEXTVAL, '홍길동', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'user1@test.com', '010-1111-1111', 'test123!@#', '테스트유저1', 'LOCAL', 'default.jpg', '/default', 0, 1);

INSERT INTO TBL_USER VALUES (SEQ_USER.NEXTVAL, '김철수', TO_DATE('1992-03-15', 'YYYY-MM-DD'), 'user2@test.com', '010-2222-2222', 'test123!@#', '테스트유저2', 'LOCAL', 'default.jpg', '/default', 0, 1);

INSERT INTO TBL_USER VALUES (SEQ_USER.NEXTVAL, '이영희', TO_DATE('1995-07-20', 'YYYY-MM-DD'), 'user3@test.com', '010-3333-3333', 'test123!@#', '테스트유저3', 'LOCAL', 'default.jpg', '/default', 0, 1);

INSERT INTO TBL_USER VALUES (SEQ_USER.NEXTVAL, '박민수', TO_DATE('1993-11-05', 'YYYY-MM-DD'), 'user4@test.com', '010-4444-4444', 'test123!@#', '테스트유저4', 'LOCAL', 'default.jpg', '/default', 0, 1);

-- 4. 게임방 생성
-- 팀전 게임방 (4명)
INSERT INTO TBL_GAME_ROOM(ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START, GAME_ROOM_PASS_KEY, GAME_ROOM_CREATE_AT)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '팀전 테스트방', 1, 'SNAKE', 1, 4, 0, NULL, SYSTIMESTAMP);

-- 개인전 게임방 (3명)
INSERT INTO TBL_GAME_ROOM(ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START, GAME_ROOM_PASS_KEY, GAME_ROOM_CREATE_AT)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '개인전 테스트방', 0, 'SNAKE', 1, 4, 0, NULL, SYSTIMESTAMP);

-- 5. 팀전 게임방 참여자 (4명)
-- 방장: USER_ID = 1 (RED 팀, 준비 안됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 1, 1, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '팀전 테스트방'), 'RED', SYSTIMESTAMP, 0, 0, 0);

-- RED 팀 플레이어: USER_ID = 2 (준비됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 0, 2, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '팀전 테스트방'), 'RED', SYSTIMESTAMP, 0, 0, 1);

-- BLUE 팀 플레이어 1: USER_ID = 3 (준비됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 0, 3, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '팀전 테스트방'), 'BLUE', SYSTIMESTAMP, 0, 0, 1);

-- BLUE 팀 플레이어 2: USER_ID = 4 (준비됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 0, 4, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '팀전 테스트방'), 'BLUE', SYSTIMESTAMP, 0, 0, 1);

-- 6. 개인전 게임방 참여자 (3명)
-- 방장: USER_ID = 1 (준비 안됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 1, 1, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '개인전 테스트방'), NULL, SYSTIMESTAMP, 0, 0, 0);

-- 플레이어 1: USER_ID = 2 (준비됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 0, 2, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '개인전 테스트방'), NULL, SYSTIMESTAMP, 0, 0, 1);

-- 플레이어 2: USER_ID = 3 (준비됨)
INSERT INTO TBL_GAME_JOIN(ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_CREATE_AT, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
VALUES (SEQ_GAME_JOIN.NEXTVAL, 0, 3, (SELECT ID FROM TBL_GAME_ROOM WHERE GAME_ROOM_TITLE = '개인전 테스트방'), NULL, SYSTIMESTAMP, 0, 0, 1);

-- ============================================
-- 확인용 쿼리
-- ============================================
-- 유저 확인
-- SELECT * FROM TBL_USER ORDER BY ID;

-- 게임방 확인
-- SELECT * FROM TBL_GAME_ROOM ORDER BY ID DESC;

-- 게임 참여자 확인
-- SELECT 
--     GJ.ID, GJ.USER_ID, GJ.GAME_ROOM_ID, GJ.GAME_JOIN_IS_HOST,
--     GJ.GAME_JOIN_TEAMCOLOR, GJ.GAME_JOIN_IS_TURN, GJ.GAME_JOIN_POSITION, GJ.GAME_JOIN_IS_READY,
--     GR.GAME_ROOM_TITLE, GR.GAME_ROOM_IS_TEAM,
--     U.USER_NICKNAME
-- FROM TBL_GAME_JOIN GJ
-- JOIN TBL_GAME_ROOM GR ON GJ.GAME_ROOM_ID = GR.ID
-- JOIN TBL_USER U ON GJ.USER_ID = U.ID
-- ORDER BY GJ.GAME_ROOM_ID, GJ.ID;

-- 팀전 방 준비 상태 확인
-- SELECT 
--     GR.GAME_ROOM_TITLE,
--     U.USER_NICKNAME,
--     GJ.USER_ID,
--     GJ.GAME_JOIN_IS_HOST,
--     GJ.GAME_JOIN_TEAMCOLOR,
--     GJ.GAME_JOIN_IS_READY
-- FROM TBL_GAME_JOIN GJ
-- JOIN TBL_GAME_ROOM GR ON GJ.GAME_ROOM_ID = GR.ID
-- JOIN TBL_USER U ON GJ.USER_ID = U.ID
-- WHERE GR.GAME_ROOM_TITLE = '팀전 테스트방'
-- ORDER BY GJ.GAME_JOIN_IS_HOST DESC, GJ.ID;
