-- ============================================
-- 게임 멀티플레이어 테스트용 완전한 SQL
-- 프론트엔드 에러 방지를 위한 최소 테이블 생성
-- ============================================

-- 1. 시퀀스 생성
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GAME_ROOM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GAME_JOIN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FOLLOW START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FOLLOW_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. 테이블 생성
-- TBL_USER
CREATE TABLE TBL_USER (
    ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    USER_BIRTHDAY DATE,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_PHONE VARCHAR2(20),
    USER_PASSWORD VARCHAR2(255),
    USER_NICKNAME VARCHAR2(50) NOT NULL,
    USER_PROVIDER VARCHAR2(20) DEFAULT 'LOCAL',
    USER_THUMBNAIL_NAME VARCHAR2(255),
    USER_THUMBNAIL_URL VARCHAR2(500),
    USER_EXP NUMBER DEFAULT 0,
    USER_LEVEL NUMBER DEFAULT 1
);

-- TBL_POST (최소 컬럼만)
CREATE TABLE TBL_POST (
    ID NUMBER PRIMARY KEY,
    POST_TITLE VARCHAR2(200),
    POST_CONTENT VARCHAR2(4000),
    POST_TYPE VARCHAR2(20),
    POST_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    POST_VIEW_COUNT NUMBER DEFAULT 0,
    USER_ID NUMBER,
    CONSTRAINT FK_POST_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID)
);

-- TBL_COMMENT (최소 컬럼만)
CREATE TABLE TBL_COMMENT (
    ID NUMBER PRIMARY KEY,
    COMMENT_DESCRIPTION VARCHAR2(4000),
    USER_ID NUMBER,
    POST_ID NUMBER,
    COMMENT_IS_ACCEPT NUMBER(1) DEFAULT 0,
    COMMENT_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_COMMENT_POST FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID)
);

-- TBL_POST_NOTIFICATION
CREATE TABLE TBL_POST_NOTIFICATION (
    ID NUMBER PRIMARY KEY,
    POST_NOTIFICATION_ACTION VARCHAR2(50),
    ACTOR_USER_ID NUMBER,
    RECEIVER_USER_ID NUMBER,
    POST_ID NUMBER,
    POST_NOTIFICATION_IS_READ NUMBER(1) DEFAULT 0,
    NOTIFICATION_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PN_USER_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_PN_USER_RECEIVER FOREIGN KEY (RECEIVER_USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_PN_POST FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID)
);

-- TBL_COMMENT_NOTIFICATION
CREATE TABLE TBL_COMMENT_NOTIFICATION (
    ID NUMBER PRIMARY KEY,
    COMMENT_NOTIFICATION_ACTION VARCHAR2(50),
    ACTOR_USER_ID NUMBER,
    RECEIVER_USER_ID NUMBER,
    COMMENT_ID NUMBER,
    COMMENT_NOTIFICATION_IS_READ NUMBER(1) DEFAULT 0,
    NOTIFICATION_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CN_USER_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_CN_USER_RECEIVER FOREIGN KEY (RECEIVER_USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_CN_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES TBL_COMMENT(ID)
);

-- TBL_FOLLOW (팔로우 관계 테이블)
CREATE TABLE TBL_FOLLOW (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    FOLLOWER_ID NUMBER NOT NULL,
    FOLLOW_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FOLLOW_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_FOLLOW_FOLLOWER FOREIGN KEY (FOLLOWER_ID) REFERENCES TBL_USER(ID)
);

-- TBL_FOLLOW_NOTIFICATION
CREATE TABLE TBL_FOLLOW_NOTIFICATION (
    ID NUMBER PRIMARY KEY,
    ACTOR_USER_ID NUMBER,
    RECEIVER_USER_ID NUMBER,
    FOLLOW_ID NUMBER,
    FOLLOW_NOTIFICATION_IS_READ NUMBER(1) DEFAULT 0,
    NOTIFICATION_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FN_USER_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_FN_USER_RECEIVER FOREIGN KEY (RECEIVER_USER_ID) REFERENCES TBL_USER(ID)
);

-- TBL_GAME_ROOM
CREATE TABLE TBL_GAME_ROOM (
    ID NUMBER PRIMARY KEY,
    GAME_ROOM_TITLE VARCHAR2(100),
    GAME_ROOM_IS_TEAM NUMBER(1) DEFAULT 0,
    GAME_ROOM_TYPE VARCHAR2(50),
    GAME_ROOM_IS_OPEN NUMBER(1) DEFAULT 1,
    GAME_ROOM_MAX_PLAYER NUMBER DEFAULT 4,
    GAME_ROOM_IS_START NUMBER(1) DEFAULT 0,
    GAME_ROOM_PASS_KEY VARCHAR2(100),
    GAME_ROOM_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- TBL_GAME_JOIN
CREATE TABLE TBL_GAME_JOIN (
    ID NUMBER PRIMARY KEY,
    GAME_JOIN_IS_HOST NUMBER(1) DEFAULT 0,
    USER_ID NUMBER NOT NULL,
    GAME_ROOM_ID NUMBER NOT NULL,
    GAME_JOIN_TEAMCOLOR VARCHAR2(20),
    GAME_JOIN_CREATE_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    GAME_JOIN_IS_TURN NUMBER(1) DEFAULT 0,
    GAME_JOIN_POSITION NUMBER DEFAULT 0,
    GAME_JOIN_IS_READY NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_GAME_JOIN_ROOM FOREIGN KEY (GAME_ROOM_ID) REFERENCES TBL_GAME_ROOM(ID),
    CONSTRAINT FK_GAME_JOIN_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID)
);

-- 3. 유저 데이터 (4명, 최소 컬럼만)
INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저1', 'test1@test.com', '테스트1', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저2', 'test2@test.com', '테스트2', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저3', 'test3@test.com', '테스트3', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저4', 'test4@test.com', '테스트4', 'test123!@#', 'LOCAL');

-- 4. 최소한의 POST 데이터 (에러 방지용)
INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_TYPE, USER_ID)
SELECT SEQ_POST.NEXTVAL, '더미 게시글', '더미 내용', 'OPEN', ID
FROM TBL_USER
WHERE USER_EMAIL = 'test1@test.com';

-- 5. 게임방 생성
INSERT INTO TBL_GAME_ROOM (ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '팀전 테스트방', 1, 'SNAKE', 1, 4, 0);

INSERT INTO TBL_GAME_ROOM (ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '개인전 테스트방', 0, 'SNAKE', 1, 4, 0);

-- 6. 팀전 게임방 참여 (4명)
INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 1, u1.ID, gr.ID, 'RED', 0, 0, 0
FROM TBL_USER u1, TBL_GAME_ROOM gr
WHERE u1.USER_EMAIL = 'test1@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u2.ID, gr.ID, 'RED', 0, 0, 1
FROM TBL_USER u2, TBL_GAME_ROOM gr
WHERE u2.USER_EMAIL = 'test2@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u3.ID, gr.ID, 'BLUE', 0, 0, 1
FROM TBL_USER u3, TBL_GAME_ROOM gr
WHERE u3.USER_EMAIL = 'test3@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u4.ID, gr.ID, 'BLUE', 0, 0, 1
FROM TBL_USER u4, TBL_GAME_ROOM gr
WHERE u4.USER_EMAIL = 'test4@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

-- 7. 개인전 게임방 참여 (3명)
INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 1, u1.ID, gr.ID, NULL, 0, 0, 0
FROM TBL_USER u1, TBL_GAME_ROOM gr
WHERE u1.USER_EMAIL = 'test1@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u2.ID, gr.ID, NULL, 0, 0, 1
FROM TBL_USER u2, TBL_GAME_ROOM gr
WHERE u2.USER_EMAIL = 'test2@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u3.ID, gr.ID, NULL, 0, 0, 1
FROM TBL_USER u3, TBL_GAME_ROOM gr
WHERE u3.USER_EMAIL = 'test3@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

-- ============================================
-- 확인용 쿼리
-- ============================================
-- SELECT * FROM TBL_USER;
-- SELECT * FROM TBL_GAME_ROOM;
-- SELECT GR.GAME_ROOM_TITLE, GJ.USER_ID, U.USER_EMAIL, GJ.GAME_JOIN_TEAMCOLOR, GJ.GAME_JOIN_IS_READY
-- FROM TBL_GAME_JOIN GJ
-- JOIN TBL_GAME_ROOM GR ON GJ.GAME_ROOM_ID = GR.ID
-- JOIN TBL_USER U ON GJ.USER_ID = U.ID
-- ORDER BY GR.ID, GJ.ID;

