-- ============================================
-- 게임 멀티플레이어 테스트용 간단한 SQL
-- 기존 유저가 있다면 유저 INSERT 부분은 건너뛰고 게임방/참여 데이터만 실행
-- ============================================

-- 1. 기존 유저 확인 (이미 있다면 이 부분은 건너뛰기)
-- SELECT ID, USER_EMAIL, USER_NICKNAME FROM TBL_USER;

-- 2. 최소한의 유저만 INSERT (필수 컬럼만, USER_BIRTHDAY는 NULL 허용)
-- 기존 유저가 있다면 이 부분도 건너뛰기
INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저1', 'test1@test.com', '테스트1', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저2', 'test2@test.com', '테스트2', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저3', 'test3@test.com', '테스트3', 'test123!@#', 'LOCAL');

INSERT INTO TBL_USER (ID, USER_NAME, USER_EMAIL, USER_NICKNAME, USER_PASSWORD, USER_PROVIDER)
VALUES (SEQ_USER.NEXTVAL, '테스트유저4', 'test4@test.com', '테스트4', 'test123!@#', 'LOCAL');

-- 3. 유저 ID 확인 (위에서 INSERT한 유저들의 ID 확인)
-- SELECT ID, USER_EMAIL FROM TBL_USER WHERE USER_EMAIL LIKE 'test%@test.com' ORDER BY ID;

-- 4. 게임방 생성 (팀전 4명)
INSERT INTO TBL_GAME_ROOM (ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '팀전 테스트방', 1, 'SNAKE', 1, 4, 0);

-- 5. 게임방 생성 (개인전 3명)
INSERT INTO TBL_GAME_ROOM (ID, GAME_ROOM_TITLE, GAME_ROOM_IS_TEAM, GAME_ROOM_TYPE, GAME_ROOM_IS_OPEN, GAME_ROOM_MAX_PLAYER, GAME_ROOM_IS_START)
VALUES (SEQ_GAME_ROOM.NEXTVAL, '개인전 테스트방', 0, 'SNAKE', 1, 4, 0);

-- 6. 게임방 ID 확인
-- SELECT ID, GAME_ROOM_TITLE FROM TBL_GAME_ROOM ORDER BY ID DESC;

-- 7. 팀전 게임방 참여 (4명)
-- 방장: USER_ID = (SELECT ID FROM TBL_USER WHERE USER_EMAIL = 'test1@test.com')
-- RED 팀: USER_ID = test1, test2
-- BLUE 팀: USER_ID = test3, test4
INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 1, u1.ID, gr.ID, 'RED', 0, 0, 0
FROM TBL_USER u1, TBL_GAME_ROOM gr
WHERE u1.USER_EMAIL = 'test1@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u2.ID, gr.ID, 'RED', 0, 0, 1
FROM TBL_USER u2, TBL_GAME_ROOM gr
WHERE u2.USER_EMAIL = 'test2@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u3.ID, gr.ID, 'BLUE', 0, 0, 1
FROM TBL_USER u3, TBL_GAME_ROOM gr
WHERE u3.USER_EMAIL = 'test3@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u4.ID, gr.ID, 'BLUE', 0, 0, 1
FROM TBL_USER u4, TBL_GAME_ROOM gr
WHERE u4.USER_EMAIL = 'test4@test.com' AND gr.GAME_ROOM_TITLE = '팀전 테스트방';

-- 8. 개인전 게임방 참여 (3명)
INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 1, u1.ID, gr.ID, NULL, 0, 0, 0
FROM TBL_USER u1, TBL_GAME_ROOM gr
WHERE u1.USER_EMAIL = 'test1@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u2.ID, gr.ID, NULL, 0, 0, 1
FROM TBL_USER u2, TBL_GAME_ROOM gr
WHERE u2.USER_EMAIL = 'test2@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

INSERT INTO TBL_GAME_JOIN (ID, GAME_JOIN_IS_HOST, USER_ID, GAME_ROOM_ID, GAME_JOIN_TEAMCOLOR, GAME_JOIN_IS_TURN, GAME_JOIN_POSITION, GAME_JOIN_IS_READY)
SELECT SEQ_GAME_JOIN.NEXTVAL, 0, u3.ID, gr.ID, NULL, 0, 0, 1
FROM TBL_USER u3, TBL_GAME_ROOM gr
WHERE u3.USER_EMAIL = 'test3@test.com' AND gr.GAME_ROOM_TITLE = '개인전 테스트방';

-- ============================================
-- 확인용 쿼리
-- ============================================
-- 게임방과 참여자 확인
-- SELECT 
--     GR.ID AS ROOM_ID,
--     GR.GAME_ROOM_TITLE,
--     GR.GAME_ROOM_IS_TEAM,
--     GJ.USER_ID,
--     U.USER_EMAIL,
--     U.USER_NICKNAME,
--     GJ.GAME_JOIN_IS_HOST,
--     GJ.GAME_JOIN_TEAMCOLOR,
--     GJ.GAME_JOIN_IS_READY
-- FROM TBL_GAME_ROOM GR
-- JOIN TBL_GAME_JOIN GJ ON GR.ID = GJ.GAME_ROOM_ID
-- JOIN TBL_USER U ON GJ.USER_ID = U.ID
-- ORDER BY GR.ID, GJ.ID;

